--- !dit.random.org,2008-03-06/project 
name: dit-gui
version: "0.5"
components: 
- !dit.random.org,2008-03-06/component 
  name: dit-gui
releases: 
- !dit.random.org,2008-03-06/release 
  name: v0.0.1
  status: :released
  release_time: 2014-10-11 16:25:53.253218 Z
  log_events: 
  - - 2014-10-07 20:10:21.855007 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - |-
      First version that can talk to dit
      and show something
  - - 2014-10-11 16:25:53.253226 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      First functional version has been completed.
      This release exceeds all expectations.
- !dit.random.org,2008-03-06/release 
  name: v0.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-07 17:33:02.908635 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - First functional version. Minimal functionality.
- !dit.random.org,2008-03-06/release 
  name: v0.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-07 17:33:40.341226 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - 2nd version with more features added.
- !dit.random.org,2008-03-06/release 
  name: v0.3
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-07 17:34:55.708186 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - A feature complete release.
- !dit.random.org,2008-03-06/release 
  name: v0.4
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-10 09:10:13.146682 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Better usability beyond original Ditz.
- !dit.random.org,2008-03-06/release 
  name: v0.5
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-15 12:17:53.703125 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Extended functionality release.
