components:
- ''
name: ditz-gui
releases:
- log_events:
  - - 2014-10-07 20:10:21.855007 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - |-
      First version that can talk to ditz
      and show something
  - - 2014-10-11 16:25:53.253226 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      First functional version has been completed.
      This release exceeds all expectations.
  name: v0.0.1
  release_time: 2014-10-11 16:25:53.253218 Z
  status: :released
- log_events:
  - - 2014-10-07 17:33:02.908635 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - First functional version. Minimal functionality.
  - - 2014-10-18 21:42:18.331868 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      This release is a functional version.
      The software can be used to handle the
      issues of this project.

      Only the features that are still missing
      need to be done from the command line.
  name: v0.1
  release_time: 2014-10-18 21:42:18.331858 Z
  status: :released
- log_events:
  - - 2014-10-18 21:00:27.614329 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Editing of issues added to v0.1.
  - - 2014-12-08 16:55:38.530949 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      First enhancement and bug fix release for v0.1.
      Software coming along nicely.
  name: v0.1.1
  release_time: 2014-12-08 16:55:38.530939 Z
  status: :released
- log_events:
  - - 2014-10-18 21:07:19.438204 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Another fix release. Polishing the v0.1.
  - - 2014-12-16 21:55:43.352072 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      Finally. This was hard as there were many tasks, but
      not much visible results. The program is coming
      along nicely.
  name: v0.1.2
  release_time: 2014-12-16 21:55:43.352062 Z
  status: :released
- log_events:
  - - 2014-10-07 17:33:40.341226 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - 2nd version with more features added.
  name: v0.2
  release_time: null
  status: :unreleased
- log_events:
  - - 2014-10-07 17:34:55.708186 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - A feature complete release.
  name: v0.3
  release_time: null
  status: :unreleased
- log_events:
  - - 2014-10-10 09:10:13.146682 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Better usability beyond original Ditz.
  name: v0.4
  release_time: null
  status: :unreleased
- log_events:
  - - 2014-10-15 12:17:53.703125 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Extended functionality release.
  name: v0.5
  release_time: null
  status: :unreleased
- log_events:
  - - 2015-01-12 15:45:41.437053 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - First bugfix release for 0.2 branch.
  - - 2015-01-12 16:06:53.973565 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - edited
    - Just testing if editing releases now works cleanly.
  - - 2015-01-12 16:07:10.477706 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - edited
    - Ok. Seems to work.
  name: v0.2.1
  release_time: '-'
  status: :unreleased
version: '0.5'
