--- !ditz.rubyforge.org,2008-03-06/project 
name: ditz-gui
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ditz-gui
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.0.1
  status: :released
  release_time: 2014-10-11 16:25:53.253218 Z
  log_events: 
  - - 2014-10-07 20:10:21.855007 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - |-
      First version that can talk to ditz
      and show something
  - - 2014-10-11 16:25:53.253226 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      First functional version has been completed.
      This release exceeds all expectations.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1
  status: :released
  release_time: 2014-10-18 21:42:18.331858 Z
  log_events: 
  - - 2014-10-07 17:33:02.908635 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - First functional version. Minimal functionality.
  - - 2014-10-18 21:42:18.331868 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      This release is a functional version.
      The software can be used to handle the
      issues of this project.
      
      Only the features that are still missing
      need to be done from the command line.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1.1
  status: :released
  release_time: 2014-12-08 16:55:38.530939 Z
  log_events: 
  - - 2014-10-18 21:00:27.614329 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Editing of issues added to v0.1.
  - - 2014-12-08 16:55:38.530949 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - released
    - |-
      First enhancement and bug fix release for v0.1.
      Software coming along nicely.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-18 21:07:19.438204 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Another fix release. Polishing the v0.1.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-07 17:33:40.341226 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - 2nd version with more features added.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.3
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-07 17:34:55.708186 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - A feature complete release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.4
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-10 09:10:13.146682 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Better usability beyond original Ditz.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.5
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-15 12:17:53.703125 Z
    - Markus Silvan <markus.silvan@iki.fi>
    - created
    - Extended functionality release.
